CFCONFIG-21 adding commands to directly add templates
Ortus-Solutions/commandbox-cfconfig pull request #22
Opened 2022-05-05 11:13 UTC by cybersonic

2022-05-05 18:47 UTC, bdw429s requested changes
Looks great, just one quick question about some debugging.

2022-05-05 18:47 UTC, bdw429s commented on commands/cfconfig/debugtemplates/delete.cfc
> +		print.redLine(templates);
@cybersonic Is this debugging we can remove?

2022-05-05 19:23 UTC, cybersonic commented
Oh yeah. Great catch. I will remove!

Mark Drew

> On 5 May 2022, at 19:47, Brad Wood ***@***.***> wrote:
> 
> ﻿
> @bdw429s requested changes on this pull request.
> 
> Looks great, just one quick question about some debugging.
> 
> In commands/cfconfig/debugtemplates/delete.cfc:
> 
> > +			error( e.message, e.detail ?: '' );
> +		}
> +			
> +		if( !toDetails.path.len() ) {
> +			error( "The location for the server couldn't be determined.  Please check your spelling." );
> +		}
> +		
> +		// Read existing config
> +		var oConfig = CFConfigService.determineProvider( toDetails.format, toDetails.version )
> +			.read( toDetails.path );
> +
> +		// Get the caches and remove the requested one
> +		var templates = oConfig.getDebuggingTemplates() ?: {};
> +		templates.delete( label );	
> +
> +		print.redLine(templates);
> @cybersonic Is this debugging we can remove?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.

2022-05-06 08:29 UTC, cybersonic commented
I have updated the PR

2022-05-06 13:44 UTC, merged

2022-05-09 17:15 UTC, bdw429s commented
FYI, I cleaned up a couple things and pushed a new version of `commandbox-cfconfig` this morning.